### ISSUE TITLE
TypeError: Rdp.registerTabActor(...) is undefined

### ISSUE THREAD

**Issue by jryans** [firebug/websocket-monitor#61] opened 2016-06-06 16:44 UTC
With WebSocket Monitor 0.6.2 and Nightly 2016-06-06, I get the following:

```
TypeError: Rdp.registerTabActor(...) is undefined
```

and the panel does not load.

**Comment by janodvarko** [comment] 2016-06-06 18:02
The fix goes to firebug.sdk
https://github.com/firebug/firebug.sdk/commit/bd43add69503dd8b421f8768b2d048bae9642271

(new module path for ActorRegistryFront)

Will be fixed in WebSocket Monitor 0.6.3

Honza

**Closed as completed by janodvarko** 2016-06-06 18:02 UTC
Labels: bug

**Comment by janodvarko** [comment] 2016-06-06 18:13
0.6.3 is on AMO (waiting for review ;-)

Please let me know if the problem is fixed for you now.

Honza

**Comment by jryans** [comment] 2016-06-06 18:39
Great, that seems to fix it. Review approved on AMO.

**Comment by janodvarko** [comment] 2016-06-06 18:47
Thanks!
